---
# MariaDB ConfigMap for Tuning
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-config
  namespace: erp-sandbox
data:
  custom.cnf: |
    [mysqld]
    wait_timeout = 28800
    interactive_timeout = 28800
    max_allowed_packet = 64M