version: '3.7'

services:
  mariadb:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mariadb_data:/var/lib/mysql

  redis:
    image: redis:alpine
    restart: always

  erpnext:
    build: .
    depends_on:
      - mariadb
      - redis
    ports:
      - "8000:8000"
    environment:
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - ./sites:/opt/bench/erp-bench/sites

volumes:
  mariadb_data:
