
# Frontend (Nginx)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frappe-frontend
  namespace: erp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frappe-frontend
  template:
    metadata:
      labels:
        app: frappe-frontend
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      containers:
      - name: init
        image: frappe/erpnext:v15.59.0
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        command: ["nginx-entrypoint.sh"]
        ports:
        - containerPort: 8080
        env:
        - name: BACKEND
          value: "frappe-backend:8000"
        - name: FRAPPE_SITE_NAME_HEADER
          value: "erp.amoaman.com"
        - name: SOCKETIO
          value: "frappe-websocket:9000"
        - name: UPSTREAM_REAL_IP_ADDRESS
          value: "127.0.0.1"
        - name: UPSTREAM_REAL_IP_HEADER
          value: "X-Forwarded-For"
        - name: UPSTREAM_REAL_IP_RECURSIVE
          value: "off"
        - name: PROXY_READ_TIMEOUT
          value: "120"
        - name: CLIENT_MAX_BODY_SIZE
          value: "50m"
        volumeMounts:
        - name: sites
          mountPath: /home/frappe/frappe-bench/sites
        - name: logs
          mountPath: /home/frappe/frappe-bench/logs
      volumes:
      - name: sites
        persistentVolumeClaim:
          claimName: frappe-sites
      - name: logs
        persistentVolumeClaim:
          claimName: frappe-logs
---