
---
# MariaDB
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: erp-sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:10.6
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: frappe-secrets
              key: db_root_password
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mariadb-data
          mountPath: /var/lib/mysql
        - name: config
          mountPath: /etc/mysql/conf.d
        args:
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
        - --skip-character-set-client-handshake
        - --ignore-db-dir=lost+found
      volumes:
      - name: mariadb-data
        persistentVolumeClaim:
          claimName: mariadb-data
      - name: config
        configMap:
          name: mariadb-config
---