apiVersion: v1
kind: Service
metadata:
  name: frappe-frontend
  namespace: erp
spec:
  selector:
    app: frappe-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 31999
  type: NodePort