# Redis Queue
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-queue
  namespace: erp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-queue
  template:
    metadata:
      labels:
        app: redis-queue
    spec:
      containers:
      - name: redis-queue
        image: redis:6.2-alpine
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-queue-data
          mountPath: /data
      volumes:
      - name: redis-queue-data
        persistentVolumeClaim:
          claimName: redis-queue-data
---