apiVersion: v1
kind: Service
metadata:
  name: frappe-websocket
  namespace: erp-sandbox
spec:
  selector:
    app: frappe-websocket
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
