---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frappe-logs
  namespace: erp
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi