---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-queue-data
  namespace: erp
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
