
---
# Secret for Sensitive Credentials
apiVersion: v1
kind: Secret
metadata:
  name: frappe-secrets
  namespace: erp
type: Opaque
data:
  db_root_password: YWRtaW4= # Base64-encoded "admin" (replace with a stronger password)
  admin_password: YWRtaW4=   # Base64-encoded "admin" (replace with a stronger password)
